// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGZqESY9qT6vl19ir9APdAdLWfjyKhDI',
    appId: '1:627124722922:web:ee248186b03c73fa184b93',
    messagingSenderId: '627124722922',
    projectId: 'auth-project-1ecc0',
    authDomain: 'auth-project-1ecc0.firebaseapp.com',
    storageBucket: 'auth-project-1ecc0.firebasestorage.app',
    measurementId: 'G-QHC2CP0Q25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLErqY3b15T_EdFVf1cKPMjA2PsTJbxGc',
    appId: '1:627124722922:android:bc1fd0efc08e7ce6184b93',
    messagingSenderId: '627124722922',
    projectId: 'auth-project-1ecc0',
    storageBucket: 'auth-project-1ecc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XRGKyjvV6o1sgSRekJIMPkQ7w1vbl_A',
    appId: '1:627124722922:ios:5229d13e61b37554184b93',
    messagingSenderId: '627124722922',
    projectId: 'auth-project-1ecc0',
    storageBucket: 'auth-project-1ecc0.firebasestorage.app',
    iosClientId: '627124722922-e5rnmc1a56ueeiaaprfie1u7b3erau6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3XRGKyjvV6o1sgSRekJIMPkQ7w1vbl_A',
    appId: '1:627124722922:ios:5229d13e61b37554184b93',
    messagingSenderId: '627124722922',
    projectId: 'auth-project-1ecc0',
    storageBucket: 'auth-project-1ecc0.firebasestorage.app',
    iosClientId: '627124722922-e5rnmc1a56ueeiaaprfie1u7b3erau6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGZqESY9qT6vl19ir9APdAdLWfjyKhDI',
    appId: '1:627124722922:web:261a7f98412ecee6184b93',
    messagingSenderId: '627124722922',
    projectId: 'auth-project-1ecc0',
    authDomain: 'auth-project-1ecc0.firebaseapp.com',
    storageBucket: 'auth-project-1ecc0.firebasestorage.app',
    measurementId: 'G-EDW6JZKH5D',
  );
}
